url: https://jiwonjung94.github.io

default_locale: en

title:
  ko: 라이브러리
  en: Library
  vi: Thư viện

subtitle:
  ko: "누구에게나, 어디서나 — 무료로 읽는 책들."
  en: "Books, free to read for anyone, anywhere."
  vi: "Sách miễn phí để đọc, cho mọi người, ở mọi nơi."
views_url: https://book-views.jiwon8297.workers.dev

verification:
  google: "a-KdWYTExOniU2W2iBfcXF02C2-MA8_64TMXzp7ZjhI"
  naver: "8e8bf4d3cb69bb3bb59feac68f66fd9e880309da"
  bing: "0EF86CC3EAA92577B417E2B49420B259"
